/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Report service liveness and the running application version.
     */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/calculate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Calculate
     * @description Compute the annual carbon footprint breakdown for the supplied inputs.
     */
    post: operations["calculate_api_calculate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/insights": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Insights
     * @description Return personalized reduction advice (Gemini, with rule-based fallback).
     *
     *     Rate-limited to 10 requests/minute per IP to protect Vertex AI quota and
     *     billing. The ``request`` parameter is required by SlowAPI's key function.
     */
    post: operations["insights_api_insights_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/entries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Entry
     * @description Persist a footprint entry for the (anonymous) device.
     */
    post: operations["create_entry_api_entries_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/entries/{device_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Entries
     * @description Return a device's footprint history, newest first.
     */
    get: operations["list_entries_api_entries__device_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * CarFuel
     * @description Car drivetrain type, which determines the per-km emission factor.
     * @enum {string}
     */
    CarFuel: "petrol" | "diesel" | "hybrid" | "electric";
    /**
     * CarbonInput
     * @description Full set of lifestyle inputs for a footprint estimate.
     */
    "CarbonInput-Input": {
      transport?: components["schemas"]["TransportInput"];
      home?: components["schemas"]["HomeInput"];
      /** @default medium_meat */
      diet: components["schemas"]["DietType"];
      consumption?: components["schemas"]["ConsumptionInput"];
    };
    /**
     * CarbonInput
     * @description Full set of lifestyle inputs for a footprint estimate.
     */
    "CarbonInput-Output": {
      transport?: components["schemas"]["TransportInput"];
      home?: components["schemas"]["HomeInput"];
      /** @default medium_meat */
      diet: components["schemas"]["DietType"];
      consumption?: components["schemas"]["ConsumptionInput"];
    };
    /**
     * Comparison
     * @description The user's total in context: global average and sustainable target.
     */
    Comparison: {
      /** Global Average Annual Kg */
      global_average_annual_kg: number;
      /** Sustainable Target Annual Kg */
      sustainable_target_annual_kg: number;
      /** Ratio To Global Average */
      ratio_to_global_average: number;
      /** Ratio To Sustainable Target */
      ratio_to_sustainable_target: number;
    };
    /**
     * ConsumptionInput
     * @description Consumer goods spending and landfill waste.
     */
    ConsumptionInput: {
      /**
       * Goods Spend Usd Per Month
       * @default 0
       */
      goods_spend_usd_per_month: number;
      /**
       * Waste Kg Per Week
       * @default 0
       */
      waste_kg_per_week: number;
    };
    /**
     * DietType
     * @description Diet profile, mapped to an annual food-production footprint.
     * @enum {string}
     */
    DietType: "heavy_meat" | "medium_meat" | "low_meat" | "pescatarian" | "vegetarian" | "vegan";
    /**
     * Entry
     * @description A stored footprint snapshot, as returned by the API.
     */
    Entry: {
      /** Device Id */
      device_id: string;
      input: components["schemas"]["CarbonInput-Output"];
      result: components["schemas"]["FootprintResult"];
      /** Id */
      id: string;
      /** Created At */
      created_at: string;
    };
    /**
     * EntryCreate
     * @description Request payload to save a footprint snapshot for an anonymous device.
     */
    EntryCreate: {
      /** Device Id */
      device_id: string;
      input: components["schemas"]["CarbonInput-Input"];
      result: components["schemas"]["FootprintResult"];
    };
    /**
     * FootprintResult
     * @description Per-category annual breakdown (kg CO2e) plus totals and context.
     */
    FootprintResult: {
      /** Breakdown Kg */
      breakdown_kg: {
        [key: string]: number;
      };
      /** Total Annual Kg */
      total_annual_kg: number;
      /** Total Annual Tonnes */
      total_annual_tonnes: number;
      comparison: components["schemas"]["Comparison"];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HomeInput
     * @description Monthly household energy use, shared across the household size.
     */
    HomeInput: {
      /**
       * Electricity Kwh Per Month
       * @default 0
       */
      electricity_kwh_per_month: number;
      /**
       * Natural Gas Kwh Per Month
       * @default 0
       */
      natural_gas_kwh_per_month: number;
      /**
       * Household Size
       * @default 1
       */
      household_size: number;
    };
    /**
     * InsightsResponse
     * @description Personalized advice: a summary plus ranked recommendations.
     */
    InsightsResponse: {
      /** Summary */
      summary: string;
      /** Recommendations */
      recommendations: components["schemas"]["Recommendation"][];
      /**
       * Source
       * @enum {string}
       */
      source: "gemini" | "rules" | "cache";
    };
    /**
     * Recommendation
     * @description One concrete reduction action with a quantified annual saving.
     */
    Recommendation: {
      /**
       * Category
       * @enum {string}
       */
      category: "transport" | "home" | "diet" | "consumption";
      /** Action */
      action: string;
      /** Estimated Annual Savings Kg */
      estimated_annual_savings_kg: number;
    };
    /**
     * TransportInput
     * @description Weekly travel habits plus yearly flight counts.
     */
    TransportInput: {
      /**
       * Car Km Per Week
       * @default 0
       */
      car_km_per_week: number;
      /** @default petrol */
      car_fuel: components["schemas"]["CarFuel"];
      /**
       * Public Transit Km Per Week
       * @default 0
       */
      public_transit_km_per_week: number;
      /**
       * Short Haul Flights Per Year
       * @default 0
       */
      short_haul_flights_per_year: number;
      /**
       * Long Haul Flights Per Year
       * @default 0
       */
      long_haul_flights_per_year: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  calculate_api_calculate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CarbonInput-Input"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FootprintResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  insights_api_insights_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CarbonInput-Input"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InsightsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_entry_api_entries_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EntryCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Entry"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_entries_api_entries__device_id__get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path: {
        device_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Entry"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
